version: "3.6"

services:
  mysql:
    build: "./posgres"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret"
      MYSQL_DATABASE: "devdb"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbpassword"
    ports:
      - "33060"
